# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

    ide: 'phpstorm://open?file=%%f&line=%%l'

when@test:
    framework:
        error_controller: null
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
