jms_serializer:
    enum_support: true
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'

    handlers:
        datetime:
            default_format:   "Y-m-d\\TH:i:sP" # ATOM
            default_timezone: "UTC"

    default_context:
        serialization:
            serialize_null: true
        deserialization:
            serialize_null: true

    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'

    metadata:
        auto_detection: true

when@prod:
    jms_serializer:
        visitors:
            json_serialization:
                options:
                    - JSON_UNESCAPED_SLASHES
                    - JSON_PRESERVE_ZERO_FRACTION

when@dev:
    jms_serializer:
        visitors:
            json_serialization:
                options:
                    - JSON_PRETTY_PRINT
                    - JSON_UNESCAPED_SLASHES
                    - JSON_PRESERVE_ZERO_FRACTION
