# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # setup the default resolver
    resolvers:
        default:
            web_path: ~ # use the default web path

    # your filter sets are defined here
    filter_sets:
        cache: ~ # use the default cache configuration

        app_logo_png:
            format: png
            quality: 80
            filters:
                thumbnail: { size: [ 120, 30 ], mode: inset }
        app_logo_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [ 120, 30 ], mode: inset }

        movie_vertical_png:
            format: png
            quality: 80
            filters:
                thumbnail: { size: [ 110, 160 ], mode: inset }
        movie_vertical_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [ 110, 160 ], mode: inset }

        movie_horizontal_png:
            format: png
            quality: 80
            filters:
                thumbnail: { size: [ 212, 120 ], mode: inset }
        movie_horizontal_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [ 212, 120 ], mode: inset }

        movie_modal_png:
            format: png
            quality: 80
            filters:
                thumbnail: { size: [ 350, 200 ], mode: inset }
        movie_modal_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [ 350, 200 ], mode: inset }

