# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:

    # Trusted device feature
    trusted_device:
        enabled: true                 # If the trusted device feature should be enabled
        lifetime: 5184000              # Lifetime of the trusted device token
        extend_lifetime: true         # Automatically extend lifetime of the trusted cookie on re-login
        cookie_name: trusted_device    # Name of the trusted device cookie
        cookie_secure: true           # true|false|auto Set the 'Secure' (HTTPS Only) flag on the trusted device cookie
#        cookie_same_site: "lax"        # The same-site option of the cookie, can be "lax", "strict" or null
#        cookie_domain: ".example.com"  # Domain to use when setting the cookie, fallback to the request domain if not set
#        cookie_path: "/"               # Path to use when setting the cookie

    # Backup codes feature
    backup_codes:
        enabled: true

    # Email authentication config
    email:
        enabled: true                  # If email authentication should be enabled, default false
        sender_email: no-reply@example.com   # Sender email address
        sender_name: Skeleton          # Sender name
        digits: 6                      # Number of digits in authentication code
        template: account/2fa_form.html.twig   # Template used to render the authentication form

    # Google Authenticator config
    google:
        enabled: true                             # If Google Authenticator should be enabled, default false
        server_name: Skeleton                     # Server name used in QR code
        issuer: Login                             # Issuer name used in QR code
        digits: 6                                 # Number of digits in authentication code
        leeway: 30                                # Acceptable time drift in seconds, must be less or equal than 30 seconds
        template: account/2fa_form.html.twig     # Template used to render the authentication form

    # TOTP authentication config
    totp:
        enabled: true                            # If TOTP authentication should be enabled, default false
        server_name: Skeleton                    # Server name used in QR code
        issuer: Login                            # Issuer name used in QR code
        leeway: 30                               # Acceptable time drift in seconds, must be less or equal than the TOTP period
        template: account/2fa_form.html.twig    # Template used to render the authentication form

    # The security token classes, which trigger two-factor authentication.
    # By default the bundle only reacts to Symfony's username+password authentication. If you want to enable
    # two-factor authentication for other authentication methods, add their security token classes.
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

when@test:
    scheb_two_factor:
        # A list of IP addresses or netmasks, which will not trigger two-factor authentication.
        # Supports IPv4, IPv6 and IP subnet masks.
        ip_whitelist:
            - 127.0.0.1  # One IPv4
