security:
    password_hashers:
        harsh:
            algorithm: auto
            memory_cost: 4092
            time_cost: 10
    providers:
        users:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        refresh:
            pattern: ^/auth/login/refresh
            stateless: true
            refresh_jwt:
                check_path: /auth/login/refresh
        login:
            pattern: ^/auth/login$
            stateless: true
            json_login:
                check_path: /auth/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        admin:
            pattern: ^/admin
            form_login:
                login_path: /admin/login
                check_path: /admin/login
                default_target_path: /admin
                use_referer: true
            logout:
                path: /admin/logout
                target: /admin/login
        documentation:
            pattern: ^/documentation$
            security: false
        documentation_json:
            pattern: ^/documentation.json$
            security: false
        public:
            pattern: ^/public/
            security: false
        main:
            stateless: true
            entry_point: jwt
            provider: users
            jwt: ~

    access_control:
        - { path: ^/(auth|public)/, roles: PUBLIC_ACCESS }
        - { path: ^/admin/login,    roles: PUBLIC_ACCESS }
        - { path: ^/admin,          roles: [ ROLE_ADMIN ] }
        - { path: ^/,               roles: [ IS_AUTHENTICATED_FULLY, ROLE_USER ] }

    role_hierarchy:
        ROLE_ADMIN: [ ROLE_USER ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
