security:
    password_hashers:
        harsh:
            algorithm: auto
            memory_cost: 4092
            time_cost: 10
    providers:
        users:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern:
                - ^/_profiler/
                - ^/_wdt/
                - ^/css/
                - ^/images/
                - ^/js/
                - ^/documentation/
                - ^/documentation.json/
            security: false
        login:
            pattern: ^/api/auth/login$
            stateless: true
            json_login:
                check_path: /api/auth/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        refresh:
            pattern: ^/api/auth/refresh
            stateless: true
            refresh_jwt:
                check_path: /api/auth/refresh
        auth:
            pattern:
                - ^/api/auth/register
                - ^/api/auth/recover
                - ^/api/auth/reset_password
            security: false
        api:
            pattern: ^/api/
            stateless: true
            entry_point: jwt
            provider: users
            jwt: ~
        main:
            provider: users
            form_login:
                login_path: /account/login
                check_path: /account/login
                default_target_path: /admin
                use_referer: true
                always_use_default_target_path: true
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
            logout:
                path: /admin/logout
                target: /

    access_control:
        # EasyAdmin
        - { path: ^/admin,                  roles: [ ROLE_ADMIN ] }
        # Api Related
        - { path: ^/api/auth/,              roles: PUBLIC_ACCESS }
        - { path: ^/api,                    roles: [ IS_AUTHENTICATED_FULLY, ROLE_USER ] }
        # App Related
        - { path: ^/account/2fa,            roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/account/,               roles: PUBLIC_ACCESS }
        - { path: ^/,                       roles: PUBLIC_ACCESS }

    role_hierarchy:
        ROLE_ADMIN: [ ROLE_USER ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
