proxy:
    domains:
        - app

# HTTP server settings
http:
    preferred_port: 8000

# run the server in the background
daemon: true

workers:
    # Built-in Encore integration
    npm_encore_watch: ~

    # Messenger consumer with file watching
    messenger_consume_async:
        cmd: [ 'symfony', 'console', 'messenger:consume', 'async' ]
        watch: [ 'config', 'src', 'templates', 'vendor' ]

    # Custom commands
    build_assets:
        cmd: [ 'npm', 'run', 'watch' ]

    # Auto-start Docker Compose
    docker_compose: ~
